name: Build and push CKAN 2.11 images

on: push

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-docker-publish.yml
    with:
      ckan-major-version: "2.11"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
